version: '2.1'
services:
  app:
    image: send
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn send.wsgi:application --bind 0.0.0.0:8080"
    environment: 
      ALLOWED_HOSTS: send,localhost
      DATABASE_URL: sqlite:////database/db.sqlite3
    ports:
      - '8080:8080'
    volumes:
      - database:/database/
volumes:
  database: {}
