# Generated by Django 4.0.1 on 2022-02-07 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='staticfile/'),
            preserve_default=False,
        ),
    ]
